---
- name: Install apache httpd
  apt:
    name: apache2
    state: latest
    update_cache: yes

- name: Install nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: Install apache httpd
  apt:
    pkg:
    - ufw