---
- name: Install apache httpd
  apt:
    name: apache2
    state: absent
    update_cache: yes

- name: Install nginx
  apt:
    name: nginx
    state: absent
    update_cache: yes

- name: ufw
  apt:
    pkg:
    - ufw
    state: present